### ISSUE TITLE
Support for local xlsx or other formats

### ISSUE THREAD

**Issue by arteven** [DEENUU1/job-scraper#1]
Hi!
I noticed that the only option to store results is Google Spreadsheet, it there any plan to support local files like eg .xlsx (Open XML) or markdown tables?

**Comment by DEENUU1** [comment]
Dobry pomysł, dodam dzisiaj coś

**Comment by DEENUU1** [comment]
Dodane, domyślnie dane są zapisywane do pliku .xlsx

**Comment by arteven** [comment]
dzięki, wypróbuję :)
