### ISSUE TITLE
Problem when scraping data from theprotocol.it website

### ISSUE THREAD

**Issue by SebastianSlezak** [DEENUU1/job-scraper#2]
**Short Description**
Job listings from theprotocol.it do not scrape.

**Detailed Description**
The problem occurs every time we want to scrape data from theprotocol.it.
The bug was tested on the links:
1. [theprotocol.it 1](https://theprotocol.it/filtry/trainee,assistant,junior;p/krakow;wp/zdalna,stacjonarna,hybrydowa;rw)
2. [theprotocol.it 2](https://theprotocol.it/filtry/java;t/trainee,assistant;p)

For both links the error is the same, the jobs do not scrape and in the logs fly endlessly looped messages like the following:
```prolog
Successfully visited https://theprotocol.it/filtry/trainee,assistant,junior;p/krakow;wp/zdalna,stacjonarna,hybrydowa;rw&pageNumber=1
Found 53 job offers
Successfully visited https://theprotocol.it/filtry/trainee,assistant,junior;p/krakow;wp/zdalna,stacjonarna,hybrydowa;rw&pageNumber=2
Found 53 job offers
Successfully visited https://theprotocol.it/filtry/trainee,assistant,junior;p/krakow;wp/zdalna,stacjonarna,hybrydowa;rw&pageNumber=3
Found 53 job offers
Successfully visited https://theprotocol.it/filtry/trainee,assistant,junior;p/krakow;wp/zdalna,stacjonarna,hybrydowa;rw&pageNumber=4
Found 53 job offers
Successfully visited https://theprotocol.it/filtry/trainee,assistant,junior;p/krakow;wp/zdalna,stacjonarna,hybrydowa;rw&pageNumber=5
Found 53 job offers
Successfully visited https://theprotocol.it/filtry/trainee,assistant,junior;p/krakow;wp/zdalna,stacjonarna,hybrydowa;rw&pageNumber=6
Found 53 job offers
```

**Steps to Reproduction**
1. Adding a link to "websites," for example [theprotocol.it](https://theprotocol.it/filtry/trainee,assistant,junior;p/krakow;wp/zdalna,stacjonarna,hybrydowa;rw) or the one that is given in the documentation [link theprotocol.it from the documentation](https://theprotocol.it/filtry/java;t/trainee,assistant;p)
2. Running the script

**Expected Behavior**
Scraping jobs from theprotocol.it

**Additional Information**
I was scraping job listings into a google sheet.
Scraping from other sites worked fine, only with theprotocol.it there was a loop and the listings would not add to the google sheet.

**Comment by DEENUU1** [comment]
This is a problem with pagination.

For example, go to this link https://theprotocol.it/filtry/trainee,assistant,junior;p/krakow;wp/zdalna,stacjonarna,hybrydowa;rw 
and click on the first offer from the list and then copy the url 

![obraz](https://github.com/DEENUU1/job-scraper/assets/111304236/6507eac1-beba-43fa-81e4-4d3e096c4d16)

Offers view should looks like this 

![obraz](https://github.com/DEENUU1/job-scraper/assets/111304236/f43a10ea-2a39-4476-8cf7-2c64cd0f026d)

**Comment by SebastianSlezak** [comment]
After following the steps you indicated, everything scrapes correctly.
